/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import org.example.app.App
import org.example.app.Fecha

fun main() {
    println(App().greeting)
    println(Fecha(29, 5, 2026).toString())
}